language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y XXX

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test

os:
  - linux
